### ISSUE TITLE
Coastline by country?

### ISSUE THREAD

**Issue by tetekos** [fossgis/osmdata#16]
Is there an option to download coastlines by country? thanks

**Comment by joto** [comment]
No. Download everything (it isn't that much) and split it yourself with something like ogr2ogr.

**Comment by tetekos** [comment]
I have downloaded already. The only thing this datasets has as feature is FID. So in order for my to select a country's coastline I need to know which lines belong to what country. Does that make sense?

**Comment by tetekos** [comment]
Do you have any suggestion how to do that?

**Comment by joto** [comment]
Off topic.
