### ISSUE TITLE
Question on the uses of Land polygons Projection: WGS84 (Large polygons are split, use for larger scales)

### ISSUE THREAD

**Issue by BlackDady** [fossgis/osmdata#18]
Hello, 

i try to use the Land polygons database on the public server : https://osmdata.openstreetmap.de/data/land-polygons.html
the database tagged WGS84 + split
i need small polygons

But when i request on a bbox as : bbox = min Longitude , min Latitude , max Longitude , max Latitude 
TestWay6 "-3.9769" "47.8918" "-3.9686" "47.8974"

i found only one polygon with 31082 points:
way_id	way_nodes_count	lon	lat
172938	31082	-3.3454813	47.6950427420495
172938	31082	-3.3465369	47.6950066
172938	31082	-3.3480089	47.6946503
172938	31082	-3.3492105	47.6942845
....

the bounds of this polygon are : 
-4.00074052810669	47.4683303833008	-2.99925947189331	48.0005073547363

<img width="977" alt="Capture d’écran 2021-08-24 à 17 37 30" src="https://user-images.githubusercontent.com/57327197/130647711-e26b3161-4693-4e29-978b-3489f362e036.png">

is that normal ?

are there another database (WGS84 projection) where the polygons are split smaller ?
 
Thanks for your job.

**Comment by joto** [comment]
I don't understand what you are asking. There is no way to ask for a bounding box on our website, you can only download all the data. I don't know where that screenshot is from, its not from our web site.

The download options we offer are the only ones we have. If you need to split the data in smaller pieces, you have to do this yourself.

**Comment by BlackDady** [comment]
Hello,

on this web site : https://osmdata.openstreetmap.de <https://osmdata.openstreetmap.de/>

In the menu « Contact me »  : https://osmdata.openstreetmap.de/contact.html <https://osmdata.openstreetmap.de/contact.html>

it’s write: you can contact us by opening an issue on our git repository.

The screen shot is just for precise which is the tile that i spoke in my question. it was provide by https://www.openstreetmap.org/export

My question was , is it normal that my tile has this size ?

But if it is normal, no problem.

i can’t split by myself because i don’t have enough any space on my computer to mount the « Lastest weekly Planet XML File » on https://planet.openstreetmap.org <https://planet.openstreetmap.org/>
(and i only have  internet by 4G with 100GB of fairuse by month ;) )

but, for the moment i work with the Land Polygons file here : https://osmdata.openstreetmap.de/data/land-polygons.html <https://osmdata.openstreetmap.de/data/land-polygons.html>
the Format: Shapefile, Projection: WGS84 (Large polygons are split, use for larger scales)

so, that work fine and big thanks for your job.

i'm making an android studio application and i use this database «Land Polygons », to determine if i am in land or in the water.
(you can see in the pictures joint on this email.)

For the moment i converted this shapefile into a SQLite DB file.
you can find my DB converted here : https://store.golden-block.fr/map-checkupdate.php?name=polygons&version=1 <https://store.golden-block.fr/map-checkupdate.php?name=polygons&version=1>

The real size is 4GB against 1GB in your Shapefile format and in the future that could but cool to use the shapefile format.
But for the moment i don’t know how to make a faster query with this format.

My query seems that :
public Cursor dbBBox(SQLiteDatabase db, double longitudeW, double longitudeE, double latitudeS, double latitudeN) {
    Cursor c = null;
    final int LIMIT_NODES_COUNT = 50000;

    String query;
    String[] args;


    // important USE CROSS JOIN TO FORCE TO USE SPACIAL INDEX
    query = String.format(
            "SELECT w.way_id, n.lon, n.lat " +
            "FROM " +

            "(SELECT w2.way_id AS way_id, count(w2.way_id) AS way_nodes_count " +
            "FROM ways w2 " +
            "CROSS JOIN way_nodes wn2 ON w2.way_id=wn2.way_id " +
            "WHERE ((max_lon>=?1 AND min_lon<=?2) AND (max_lat>=?3 AND min_lat<=?4)) " +
            "GROUP BY w2.way_id " +
            "HAVING count(w2.way_id) < %d ) w "+

            "CROSS JOIN way_nodes wn ON w.way_id=wn.way_id "+
            "INNER JOIN nodes n ON n.node_id=wn.node_id " +
            "ORDER BY w.way_id, wn.node_order", LIMIT_NODES_COUNT);

    // Important : args only done for selection parameters : not work with having parameters
    // Locale.ROOT -> To use "." decimal separator on French Device
    args = new String[]{
        String.format(Locale.ROOT,"%.4f", longitudeW-0.0001),
        String.format(Locale.ROOT,"%.4f", longitudeE+0.0001),
        String.format(Locale.ROOT,"%.4f", latitudeS-0.0001),
        String.format(Locale.ROOT,"%.4f", latitudeN+0.0001),
        //String.format("%d", LIMIT_NODES_COUNT),
    };

    return db.rawQuery(query, args);
}

i have a sub select to return all land with intersection surfaces with my bbox query. that take less of 1ms on all your land-polygons database
For the moment i don’t know if i can do it with the shapefile format but i will look for that later.


« i am in the water case »




« i am in the land case »




But you can see, i limited my  «real time Verctorial render » to 25 FPS and that is OK i am again into the range.

however, in this case i am at large of the French coast and my lands query also return a tile of the France coast with 40 000 points where my bbox of my viewer is inside a land cost tile that i don't need on this zoom.

So in this case if the land tiles were divised by 2, approximately i got 0, 1 or 2 tiles of 10 000 points by each and that to be better.

Thanks for your reply and sorry for my english level.

**Comment by joto** [comment]
Sorry, I still don't understand what your problem is, but it doesn't seem to be related to the service we are offering here.

**Comment by BlackDady** [comment]
My question is very simple.
Is it you who provide this files : https://osmdata.openstreetmap.de/data/land-polygons.html

This files were for who ? For garmin devices only ?

My question is, can you provide for me a new version with smaller tiles ?
