### ISSUE TITLE
Land polygons

### ISSUE THREAD

**Issue by haavardholm** [fossgis/osmdata#19]
Hello,
I need land polygons in my application but run into problems when I try to use your data. The non-splitted polygons, contains polygons with too many points, so I can not use these.
For the splitted polygons, there exist an overlap, which give me problems and I find hard to remove the overlap.
I have tried to download a planet-file for a country and then to run osmcoastline on that data, but unless the country is an island this do not seem to work.

What is your recommended solution ? I need polygons which are split, but which do not overlap.

Best regards
Håvard

**Comment by joto** [comment]
Download the non-splitted polygons and split them yourself. See the directories named `simplify_and_split_postgis` and `simplify_and_split_spatialite` in the [osmcoastline repo](https://github.com/osmcode/osmcoastline) for some ideas. There are many ways to do the splitting, that's really beyond the scope of this repository.
