### ISSUE TITLE
I'm looking for the coastline in 2010

### ISSUE THREAD

**Issue by TakashiRESTEC** [fossgis/osmdata#20]
Hi, this is Takashi. This is my first comment. 

I'm looking for the coastline in 2010 on Antarctic.

1.  If it is possible, please tell me the method to download.
2.  How can I check update date in the coastline product?

**Comment by joto** [comment]
1. No, this is not possible. We don't have historical data.
2. Next to each download link (for instance on https://osmdata.openstreetmap.de/data/coastlines.html it shows from when the data is)

**Comment by TakashiRESTEC** [comment]
Thanks for your answer.

I understood that there is no archive data. there are only latest dataset.

**Comment by TakashiRESTEC** [comment]
Closed. Thanks.
