### ISSUE TITLE
Generalized coastline not available for download: 404: Not Found on Server

### ISSUE THREAD

**Issue by FlorisCalkoen** [fossgis/osmdata#21]
Unfortunately the generalized coastline zoom level 8 is currently not available for download because the URL is not found on the server. 

The dataset I would like to download is coastlines generalized for z=1-8 in mercator projection [available as a download on this page](https://osmdata.openstreetmap.de/data/generalized-coastlines.html).

The URL for downloading the dataset that returns Not Found on Server [is here](https://osmdata.openstreetmap.de/download/coastlines-generalized-3857.zip)

Any clue where the dataset can be found? Previously it was available.

**Comment by joto** [comment]
The generalized coastlines have not been available for download for something like three years now. The page you linked to is a left-over from before.

**Comment by FlorisCalkoen** [comment]
Ahh shoot.. Can they be made available in another way? Thanks!

**Comment by joto** [comment]
Not unless somebody is interested enough in these to put some money towards it. See #5.

**Comment by FlorisCalkoen** [comment]
Ok thanks, I'll have a look if I can re-implement that potrace approach

**Comment by FlorisCalkoen** [comment]
@imagico, amazing, thanks. I've requested that data via your website.
