### ISSUE TITLE
Is there any schema change in the latest SHP file?

### ISSUE THREAD

**Issue by jennyhe2022** [fossgis/osmdata#22]
Our project refreshes the osm water world data one or twice a year. Last update is 2021/09. We usually download the shp file and then use shp2pgsql to convert it to sql script. 
Below is from the sql generated by shp2pgsql based on the latest shp file. 

```
SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;
BEGIN;
CREATE TABLE "water_areas" (gid serial,
"x" int4,
"y" int4);
ALTER TABLE "water_areas" ADD PRIMARY KEY (gid);
SELECT AddGeometryColumn('','water_areas','geom','4326','MULTIPOLYGON',2);
```
However, last year the table volumes are GID/FID/GEOM, would you please help to confirm whether we have any schema change in SHP file. thank you a lot.

**Comment by joto** [comment]
The data that's there is there. I don't remember any schema changes, but there might have been as a side effect from something else. Nobody complained though, so it can't be that bad.

Closing here. Please open a new issue if you are actually seeing any problems.
