### ISSUE TITLE
South Pole on coastline of Antarctica

### ISSUE THREAD

**Issue by shortjonescipher** [fossgis/osmdata#25]
When read with PyShp from land-polygons-complete-4326.zip, the polygon for Antarctica starts with a path to the South Pole and back.
>>> pts[:386]
[(180.0, -77.7028294), (180.0, -79.0), (180.0, -80.0), (180.0, -81.0), (180.0, -82.0), (180.0, -83.0), (180.0, -84.0), (180.0, -85.0), (180.0, -86.0), (180.0, -87.0), (180.0, -88.0), (180.0, -89.0), (180.0, -90.0), (179.0, -90.0), (178.0, -90.0), (177.0, -90.0), (176.0, -90.0), (175.0, -90.0), (174.0, -90.0), (173.0, -90.0), (172.0, -90.0), (171.0, -90.0), (170.0, -90.0), (169.0, -90.0), (168.0, -90.0), (167.0, -90.0), (166.0, -90.0), (165.0, -90.0), (164.0, -90.0), (163.0, -90.0), (162.0, -90.0), (161.0, -90.0), (160.0, -90.0), (159.0, -90.0), (158.0, -90.0), (157.0, -90.0), (156.0, -90.0), (155.0, -90.0), (154.0, -90.0), (153.0, -90.0), (152.0, -90.0), (151.0, -90.0), (150.0, -90.0), (149.0, -90.0), (148.0, -90.0), (147.0, -90.0), (146.0, -90.0), (145.0, -90.0), (144.0, -90.0), (143.0, -90.0), (142.0, -90.0), (141.0, -90.0), (140.0, -90.0), (139.0, -90.0), (138.0, -90.0), (137.0, -90.0), (136.0, -90.0), (135.0, -90.0), (134.0, -90.0), (133.0, -90.0), (132.0, -90.0), (131.0, -90.0), (130.0, -90.0), (129.0, -90.0), (128.0, -90.0), (127.0, -90.0), (126.0, -90.0), (125.0, -90.0), (124.0, -90.0), (123.0, -90.0), (122.0, -90.0), (121.0, -90.0), (120.0, -90.0), (119.0, -90.0), (118.0, -90.0), (117.0, -90.0), (116.0, -90.0), (115.0, -90.0), (114.0, -90.0), (113.0, -90.0), (112.0, -90.0), (111.0, -90.0), (110.0, -90.0), (109.0, -90.0), (108.0, -90.0), (107.0, -90.0), (106.0, -90.0), (105.0, -90.0), (104.0, -90.0), (103.0, -90.0), (102.0, -90.0), (101.0, -90.0), (100.0, -90.0), (99.0, -90.0), (98.0, -90.0), (97.0, -90.0), (96.0, -90.0), (95.0, -90.0), (94.0, -90.0), (93.0, -90.0), (92.0, -90.0), (91.0, -90.0), (90.0, -90.0), (89.0, -90.0), (88.0, -90.0), (87.0, -90.0), (86.0, -90.0), (85.0, -90.0), (84.0, -90.0), (83.0, -90.0), (82.0, -90.0), (81.0, -90.0), (80.0, -90.0), (79.0, -90.0), (78.0, -90.0), (77.0, -90.0), (76.0, -90.0), (75.0, -90.0), (74.0, -90.0), (73.0, -90.0), (72.0, -90.0), (71.0, -90.0), (70.0, -90.0), (69.0, -90.0), (68.0, -90.0), (67.0, -90.0), (66.0, -90.0), (65.0, -90.0), (64.0, -90.0), (63.0, -90.0), (62.0, -90.0), (61.0, -90.0), (60.0, -90.0), (59.0, -90.0), (58.0, -90.0), (57.0, -90.0), (56.0, -90.0), (55.0, -90.0), (54.0, -90.0), (53.0, -90.0), (52.0, -90.0), (51.0, -90.0), (50.0, -90.0), (49.0, -90.0), (48.0, -90.0), (47.0, -90.0), (46.0, -90.0), (45.0, -90.0), (44.0, -90.0), (43.0, -90.0), (42.0, -90.0), (41.0, -90.0), (40.0, -90.0), (39.0, -90.0), (38.0, -90.0), (37.0, -90.0), (36.0, -90.0), (35.0, -90.0), (34.0, -90.0), (33.0, -90.0), (32.0, -90.0), (31.0, -90.0), (30.0, -90.0), (29.0, -90.0), (28.0, -90.0), (27.0, -90.0), (26.0, -90.0), (25.0, -90.0), (24.0, -90.0), (23.0, -90.0), (22.0, -90.0), (21.0, -90.0), (20.0, -90.0), (19.0, -90.0), (18.0, -90.0), (17.0, -90.0), (16.0, -90.0), (15.0, -90.0), (14.0, -90.0), (13.0, -90.0), (12.0, -90.0), (11.0, -90.0), (10.0, -90.0), (9.0, -90.0), (8.0, -90.0), (7.0, -90.0), (6.0, -90.0), (5.0, -90.0), (4.0, -90.0), (3.0, -90.0), (2.0, -90.0), (1.0, -90.0), (0.0, -90.0), (-1.0, -90.0), (-2.0, -90.0), (-3.0, -90.0), (-4.0, -90.0), (-5.0, -90.0), (-6.0, -90.0), (-7.0, -90.0), (-8.0, -90.0), (-9.0, -90.0), (-10.0, -90.0), (-11.0, -90.0), (-12.0, -90.0), (-13.0, -90.0), (-14.0, -90.0), (-15.0, -90.0), (-16.0, -90.0), (-17.0, -90.0), (-18.0, -90.0), (-19.0, -90.0), (-20.0, -90.0), (-21.0, -90.0), (-22.0, -90.0), (-23.0, -90.0), (-24.0, -90.0), (-25.0, -90.0), (-26.0, -90.0), (-27.0, -90.0), (-28.0, -90.0), (-29.0, -90.0), (-30.0, -90.0), (-31.0, -90.0), (-32.0, -90.0), (-33.0, -90.0), (-34.0, -90.0), (-35.0, -90.0), (-36.0, -90.0), (-37.0, -90.0), (-38.0, -90.0), (-39.0, -90.0), (-40.0, -90.0), (-41.0, -90.0), (-42.0, -90.0), (-43.0, -90.0), (-44.0, -90.0), (-45.0, -90.0), (-46.0, -90.0), (-47.0, -90.0), (-48.0, -90.0), (-49.0, -90.0), (-50.0, -90.0), (-51.0, -90.0), (-52.0, -90.0), (-53.0, -90.0), (-54.0, -90.0), (-55.0, -90.0), (-56.0, -90.0), (-57.0, -90.0), (-58.0, -90.0), (-59.0, -90.0), (-60.0, -90.0), (-61.0, -90.0), (-62.0, -90.0), (-63.0, -90.0), (-64.0, -90.0), (-65.0, -90.0), (-66.0, -90.0), (-67.0, -90.0), (-68.0, -90.0), (-69.0, -90.0), (-70.0, -90.0), (-71.0, -90.0), (-72.0, -90.0), (-73.0, -90.0), (-74.0, -90.0), (-75.0, -90.0), (-76.0, -90.0), (-77.0, -90.0), (-78.0, -90.0), (-79.0, -90.0), (-80.0, -90.0), (-81.0, -90.0), (-82.0, -90.0), (-83.0, -90.0), (-84.0, -90.0), (-85.0, -90.0), (-86.0, -90.0), (-87.0, -90.0), (-88.0, -90.0), (-89.0, -90.0), (-90.0, -90.0), (-91.0, -90.0), (-92.0, -90.0), (-93.0, -90.0), (-94.0, -90.0), (-95.0, -90.0), (-96.0, -90.0), (-97.0, -90.0), (-98.0, -90.0), (-99.0, -90.0), (-100.0, -90.0), (-101.0, -90.0), (-102.0, -90.0), (-103.0, -90.0), (-104.0, -90.0), (-105.0, -90.0), (-106.0, -90.0), (-107.0, -90.0), (-108.0, -90.0), (-109.0, -90.0), (-110.0, -90.0), (-111.0, -90.0), (-112.0, -90.0), (-113.0, -90.0), (-114.0, -90.0), (-115.0, -90.0), (-116.0, -90.0), (-117.0, -90.0), (-118.0, -90.0), (-119.0, -90.0), (-120.0, -90.0), (-121.0, -90.0), (-122.0, -90.0), (-123.0, -90.0), (-124.0, -90.0), (-125.0, -90.0), (-126.0, -90.0), (-127.0, -90.0), (-128.0, -90.0), (-129.0, -90.0), (-130.0, -90.0), (-131.0, -90.0), (-132.0, -90.0), (-133.0, -90.0), (-134.0, -90.0), (-135.0, -90.0), (-136.0, -90.0), (-137.0, -90.0), (-138.0, -90.0), (-139.0, -90.0), (-140.0, -90.0), (-141.0, -90.0), (-142.0, -90.0), (-143.0, -90.0), (-144.0, -90.0), (-145.0, -90.0), (-146.0, -90.0), (-147.0, -90.0), (-148.0, -90.0), (-149.0, -90.0), (-150.0, -90.0), (-151.0, -90.0), (-152.0, -90.0), (-153.0, -90.0), (-154.0, -90.0), (-155.0, -90.0), (-156.0, -90.0), (-157.0, -90.0), (-158.0, -90.0), (-159.0, -90.0), (-160.0, -90.0), (-161.0, -90.0), (-162.0, -90.0), (-163.0, -90.0), (-164.0, -90.0), (-165.0, -90.0), (-166.0, -90.0), (-167.0, -90.0), (-168.0, -90.0), (-169.0, -90.0), (-170.0, -90.0), (-171.0, -90.0), (-172.0, -90.0), (-173.0, -90.0), (-174.0, -90.0), (-175.0, -90.0), (-176.0, -90.0), (-177.0, -90.0), (-178.0, -90.0), (-179.0, -90.0), (-180.0, -90.0), (-180.0, -89.0), (-180.0, -88.0), (-180.0, -87.0), (-180.0, -86.0), (-180.0, -85.0), (-180.0, -84.0), (-180.0, -83.0), (-180.0, -82.0), (-180.0, -81.0), (-180.0, -80.0), (-180.0, -79.0), (-180.0, -78.0), (-180.0, -77.7028294)]

**Comment by shortjonescipher** [comment]
That doesn't make sense. Why should the polygon for Antarctica be treated differently from any other polygon?
That path to the South Pole and back is entirely fictitious.

**Comment by joto** [comment]
Because the world is flat and ends at the antimeridian and at the pole. It is just simpler to handle like this for lots of software.
