### ISSUE TITLE
Many duplicate entries in split land polygons

### ISSUE THREAD

**Issue by myhillman** [fossgis/osmdata#26]
I am downloading the split land polygons at https://osmdata.openstreetmap.de/download/land-polygons-split-4326.zip. I am returned 809595 objects. I find this puzzling as there can only be a maximum of 360 x 180 = 64,800 squares on the Earth. Less than half of these are land, so I was expecting < 30,000 objects.

Inspecting the data, there seems to be massive duplication in the number of x,y values, i.e. there seems to be duplication in the bits of geometry stored. I'm not returning the geometry in my query, so it's not a big issue - I'm only interested in the Boolean question - Is it land or not?

Why are there so many objects? What am I missing? Is it that each square has multiple fragments? If so, it's a real shame (for performance reasons) they can't be consolidated into a single square.

**Comment by joto** [comment]
Land/water is not boolean in those squares. A square can contain a hundred islands or whatever.

**Comment by myhillman** [comment]
Thank you for a very quick response. Yes - I understand that, but I'm still not sure why there are so many duplicate bits of geometry for a square. Is it intended that the user has to stitch them all back together? Land/water is boolean in the sense that squares only exist where there is land. I am testing for no land, so the absence of a square means it's water.
