### ISSUE TITLE
Broken water-polygons-4326 in latest builds

### ISSUE THREAD

**Issue by PhantomCloak** [fossgis/osmdata#27]
As of today, I noticed a strange issue with our vector tile outputs. The water polygons are occupying all tiles, regardless of whether the tiles are water or land. After checked, I noticed that the latest water-polygons-4326 file is only 1MB, whereas it used to be between 800MB and 1GB in our previous builds, after using previous shape files everything starts to work normal, since I haven't get any deeper where the root cause is wonder if it's intentional or issue at osm data's side?.

For additional context I'm using tilemaker and stock open vector tiles format, issue that I described above can be reproducible using ./get-coastline script from tilemaker's repository.

**Comment by joto** [comment]
I can confirm that there is something wrong with that  (and all other 4326) coastline files. Thanks for the report. I am looking into it and will report back.

**Comment by joto** [comment]
Server ran out of memory. This is now fixed, current data is available again.
