### ISSUE TITLE
OSM Extract Question

### ISSUE THREAD

**Issue by justinelliotmeyers** [fossgis/osmdata#4]
Hello! Is there a way you could create a dataset for specific admin levels? Also, I am looking for an extract for places (points or polygons).  Any guidance would be appreciated!

Thanks!
Justin

**Comment by joto** [comment]
When you say "create a dataset for specific admin levels" I presume you mean boundaries. Maybe this is what you want: https://wambachers-osm.website/boundaries/ .

It is unlikely that we'll create place extracts here. You can create extracts yourself using, for instance, https://osmcode.org/osmium/ . There are many other ways to do this depending on what you need exactly. But this is not the right place to ask. Please use help.osm.org, the osm dev mailinglist or some other suitable place.
