### ISSUE TITLE
Generalized water polygons

### ISSUE THREAD

**Issue by andreynovikov** [fossgis/osmdata#5]
Are there plans to restore generalized water polygons? I've used them for overview map, they were perfectly looking...

**Comment by joto** [comment]
There are no current planes to bring them back. This is mainly because nobody has the time to update the old software and scripts and get them to run again in the new environment.

**Comment by andreynovikov** [comment]
Can you describe in brief how it was implemented? May be I can help.

**Comment by imagico** [comment]
The generalized water polygons process was based on https://github.com/imagico/coastline_gen, gdal_rasterize and potrace.

**Comment by andreynovikov** [comment]
And what is incompatible with the new environment?

**Comment by joto** [comment]
* The old system was running on an older Debian system, the new one is Debian Buster. Nobody checked what changes this might entail, probably not much.
* The scripts need to be updated to run in the new context. Also we are running on smaller virtual machines now, before we had a large server.

So the programs and scripts need to be updated for the new environment and made to run reliably and be fast enough, making sure we don't need too many ressources. Nothing here is rocket science, it just is a lot of tedious work to get everything set up properly.
