### ISSUE TITLE
Water Reduced Polygons Error

### ISSUE THREAD

**Issue by jbkalla** [fossgis/osmdata#6]
Attempting to download the reduced water polygons from https://osmdata.openstreetmap.de/data/water-reduced-polygons.html
fails.

**Comment by joto** [comment]
Yes. They are not created. Where did you get the link to that page? It shouldn't be linked anywhere, because they don't exist. The page is a left-over from before.

**Comment by jbkalla** [comment]
Ah, thanks.  Somebody sent me the link to the previous server, so I was trying to extrapolate from that to the new server.  Nothing on the new server sent me there.

----------
John B. Kalla
jkalla@caci.com
(303) 676-3000 x509
flickr<http://www.flickr.com/photos/jbkalla/>
Ad infinitum, et ultra!

________________________________

**Comment by xsfire** [comment]
I also happened upon this page.  Is there any easy-ish way to generate this data without loading the full OSM database?  This would be a very helpful supplement to the ocean water polygons for some work I'm doing
